import 'package:flutter/material.dart';

List<BoxShadow> kShadowList = [
  BoxShadow(
    color: Colors.grey[300],
    blurRadius: 24.0,
    offset: Offset(0, 10),
  ),
];

var kVegetablesList = [
  {'name': 'Bhindi', 'iconPath' : 'images/vegetables/bhindi.png'},
  {'name': 'Pepper', 'iconPath' : 'images/vegetables/pepper.png'},
  {'name': 'Cabbage', 'iconPath' : 'images/vegetables/cabbage.png'},
  {'name': 'Lauki', 'iconPath' : 'images/vegetables/lauki.png'},
  {'name': 'Karela', 'iconPath' : 'images/vegetables/karela.png'},
  {'name': 'Spinach', 'iconPath' : 'images/vegetables/spinach.png'},
  {'name': 'Parwal', 'iconPath' : 'images/vegetables/parwal.png'},
  {'name': 'Pea(Matar)', 'iconPath' : 'images/vegetables/pea.png'},
  {'name': 'Pumpkin', 'iconPath' : 'images/vegetables/pumpkin.png'},
  {'name': 'Cauliflower', 'iconPath' : 'images/vegetables/cauliflower.png'},
  {'name': 'Broccoli', 'iconPath' : 'images/vegetables/broccoli.png'},
  {'name': 'Brinjal', 'iconPath' : 'images/vegetables/brinjal.png'},
  {'name': 'Rajma', 'iconPath' : 'images/vegetables/rajma.png'},
  {'name': 'Potato', 'iconPath' : 'images/vegetables/potato.png'},
  {'name': 'Sweet Potato', 'iconPath' : 'images/vegetables/sweet_potato.png'},
  {'name': 'Beetroot', 'iconPath' : 'images/vegetables/beetroot.png'},
];

var kFruitsList = [
  {'name': 'Mango', 'iconPath' : 'images/fruits/mango.png'},
  {'name': 'Banana', 'iconPath' : 'images/fruits/banana.png'},
  {'name': 'Apple', 'iconPath' : 'images/fruits/apple.png'},
  {'name': 'Papaya', 'iconPath' : 'images/fruits/papaya.png'},
  {'name': 'Tomato', 'iconPath' : 'images/fruits/tomato.png'},
  {'name': 'Strawberry', 'iconPath' : 'images/fruits/strawberry.png'},
  {'name': 'Carrot', 'iconPath' : 'images/fruits/carrot.png'},
  {'name': 'Gooseberry(Aawla)', 'iconPath' : 'images/fruits/gooseberry.png'},
  {'name': 'Pomegranate', 'iconPath' : 'images/fruits/pomegranate.png'},
  {'name': 'Lime', 'iconPath' : 'images/fruits/lime.png'},
  {'name': 'Guava', 'iconPath' : 'images/fruits/guava.png'},
  {'name': 'Grape', 'iconPath' : 'images/fruits/grape.png'},
  {'name': 'Custard Apple', 'iconPath' : 'images/fruits/custard_apple.png'},
  {'name': 'Orange', 'iconPath' : 'images/fruits/orange.png'},
  {'name': 'Watermelon', 'iconPath' : 'images/fruits/watermelon.png'},
  {'name': 'Pineapple', 'iconPath' : 'images/fruits/pineapple.png'},
  {'name': 'Mushroom', 'iconPath' : 'images/fruits/mushroom.png'},
];

var kMixList = [
  {'name': 'Paneer', 'iconPath' : 'images/vegetables/paneer.png'},
  {'name': 'Chhole', 'iconPath' : 'images/vegetables/chhole.png'},
];

var kNonVegList = [
  {'name': 'Egg', 'iconPath' : 'images/non-veg/egg.png'},
  {'name': 'Chicken', 'iconPath' : 'images/non-veg/chicken.png'},
  {'name': 'Fish', 'iconPath' : 'images/non-veg/fish.png'},
  {'name': 'Meat', 'iconPath' : 'images/non-veg/meat.png'},
  {'name': 'Pigeon', 'iconPath' : 'images/non-veg/pigeon.png'},
  {'name': 'Beef', 'iconPath' : 'images/non-veg/beef.png'},
  {'name': 'Crab', 'iconPath' : 'images/non-veg/crab.png'},
  {'name': 'Rabbit', 'iconPath' : 'images/non-veg/rabbit.png'},
  {'name': 'Pork', 'iconPath' : 'images/non-veg/pork.png'},
];

Map<String, Image> kImageMap = {

  // vegetables
  'Bhindi' : Image.asset('images/vegetables/bhindi.png'),
  'Pepper' : Image.asset('images/vegetables/pepper.png'),
  'Cabbage' : Image.asset('images/vegetables/cabbage.png'),
  'Lauki' : Image.asset('images/vegetables/lauki.png'),
  'Karela' : Image.asset('images/vegetables/karela.png'),
  'Spinach' : Image.asset('images/vegetables/spinach.png'),
  'Parwal' : Image.asset('images/vegetables/parwal.png'),
  'Pea(Matar)' : Image.asset('images/vegetables/pea.png'),
  'Pumpkin' : Image.asset('images/vegetables/pumpkin.png'),
  'Cauliflower' : Image.asset('images/vegetables/cauliflower.png'),
  'Broccoli' : Image.asset('images/vegetables/broccoli.png'),
  'Brinjal' : Image.asset('images/vegetables/brinjal.png'),
  'Rajma' : Image.asset('images/vegetables/rajma.png'),
  'Potato' : Image.asset('images/vegetables/potato.png'),
  'Sweet Potato' : Image.asset('images/vegetables/sweet_potato.png'),
  'Beetroot' : Image.asset('images/vegetables/beetroot.png'),

  // fruits
  'Mango' : Image.asset('images/fruits/mango.png'),
  'Banana' : Image.asset('images/fruits/banana.png'),
  'Apple' : Image.asset('images/fruits/apple.png'),
  'Papaya' : Image.asset('images/fruits/papaya.png'),
  'Tomato' : Image.asset('images/fruits/Tomato.png'),
  'Strawberry' : Image.asset('images/fruits/strawberry.png'),
  'Carrot' : Image.asset('images/fruits/carrot.png'),
  'Gooseberry(Aawla)' : Image.asset('images/fruits/gooseberry.png'),
  'Pomegranate' : Image.asset('images/fruits/pomegranate.png'),
  'Lime' : Image.asset('images/fruits/lime.png'),
  'Guava' : Image.asset('images/fruits/guava.png'),
  'Grape' : Image.asset('images/fruits/grape.png'),
  'Custard Apple' : Image.asset('images/fruits/custard_apple.png'),
  'Orange' : Image.asset('images/fruits/orange.png'),
  'Watermelon' : Image.asset('images/fruits/watermelon.png'),
  'Pineapple' : Image.asset('images/fruits/pineapple.png'),
  'Mushroom' : Image.asset('images/fruits/mushroom.png'),

  // mix items
  'Paneer' : Image.asset('images/vegetables/paneer.png'),

  // non-veg
  'Egg' : Image.asset('images/non-veg/egg.png'),
  'Chicken' : Image.asset('images/non-veg/chicken.png'),
  'Fish' : Image.asset('images/non-veg/fish.png'),
  'Meat' : Image.asset('images/non-veg/meat.png'),
  'Pigeon' : Image.asset('images/non-veg/pigeon.png'),
  'Beef' : Image.asset('images/non-veg/beef.png'),
  'Crab' : Image.asset('images/non-veg/crab.png'),
  'Rabbit' : Image.asset('images/non-veg/rabbit.png'),
  'Pork' : Image.asset('images/non-veg/pork.png'),
};

Map<String, List<String>> mp = {

  /* Vegetables */
  "Bhindi" : [
    'Bhindi Masala',
    'Kurkuri Bhindi | Okra Fry',
    'Vendakkai Poriyal',
    'Vendakkai Sambar',
    'Bhindi Fry',
    'Bharli Bhendi',
    'Shahi Bhind',
    'Bharwa Bhindi',
    'Lahsuni Bhindi',
    'Bhindi Do Pyaza',
    'Aloo Bhindi',
    'Besan Bhindi',
    'Bhindi Nariyal Sabzi',
    'Bhindi Ka Salan',
    'Bhindi Rice',
  ],
  "Pepper" : [
    'Capsicum curry',
    'Capsicum fry',
    'Aloo Capsicum',
    'Stuffed Capsicum',
    'Capsicum Salan',
    'Pepper Panner',
    'Capsicum Chutney',
    'Red Capsicum Chutney',
    'Peanut Capsicum Chutney',
    'Capsicum Cheese Toast Sandwich',
    'Capsicum Rice',
  ],
  "Cabbage" : [
    'Patta Gobhi Matar',
    'Patta Gobhi Chana Dal',
    'Cabbage Paratha',
    'Cabbage Vada',
    'Cabbage Kootu',
    'Cabbage Foogath',
    'Cabbage Pakoda',
    'Cabbage Chutney',
    'Cabbage Poriyal',
    'Cabbage Bhaji',
    'Cabbage Coleslaw',
    'Weeknight Cabbage Rolls',
    'One-Pot Cabbage & Sausage Pasta',
    'Unstuffed Cabbage Rolls Bowls',
    'Veggie packed Cabbage Soup',
    'Grilled Cabbage Wedges with Spicy Lime Dressing',
    'Cabbage and Apple Slaw with Honey Lime Dressing',
    'Shredded Cabbage & Sweet Potato Slaw',
    'Roasted Cabbage Slaw with Hazelnuts & Lemon',
    'Kohlrabi & Cabbage Salad with Maple Lemon Dressing',
    'Apple Cabbage Salad with Brown Sugar Cider Vinaigrette',
  ],
  "Lauki" : [
    'Lauki Kofta Curry',
    'Bharwa Lauki',
    'Doodhi Theplas',
    'Doodhi Muthia',
    'Lauki ki Kheer',
    'Doodhi Ka Halwa',
    'Bottle Gourd, Carrot & Beetroot Halwa',
    'Lauki ka Raita',
    'Lauki Aur Pudine ka Raita',
    'Sambhar',
  ],
  "Karela" : [
    'Sukhi Karela Sabzi',
    'Onion and Karela Sabzi',
    'Karela and Capsicum sabzi',
    'Masala Karela',
    'Stuffed Karela in Makhani Gravy',
    'Masala Bharwan Karela',
    'Karela Bhindi Masala',
    'Karela Kadhi',
    'Karega Mauthias',
    'Karela Peel Kadhi',
    'Crispy Karela',
    'Karela Paratha',
    'Karela Theplas',
    'Karela Chips',
    'Karela Tikkis',
    'Malai Karela',
    'Karela Cutlet',
    'Karela Rice',
  ],
  "Spinach" : [
    'Palak Ki Sabzi',
    'Sarson Ka Saag',
    'Palak Soup',
    'Hara Bhara Kabab',
    'Aloo Palak',
    'Easy Dal Palak (Creamy Lentils With Spinach)',
    'Palak Saag',
    'Palak Paratha',
    'Aloo Palak Paratha',
    'Palak Corn',
    'Palak Pakoda',
    'Palak Mushroom',
    'Palak Khichdi',
    'Palak Chole',
    'One Pot Cheesy Spinach Corn',
    'Paneer Palak Bhurji',
    'Paneer Palak Roll',
    'Palak Ka Raita',
    'Methi Palak Saag Paneer',
    'Palak Chaat',
    'Corn Spinach Pulao',
    'Methi Chaman',
    'Palak Puri',
    'Palak Kofta',
  ],
  "Parwal" : [
    'Parwal Pyarelal',
    'Parwal Ki Mithai',
    'Parwal Fry',
    'Parwal Deep Fry',
    'Parwal Kalunga',
    'Dry Stuffed Parwal',
    'Parwal Korma',
    'Dahi Parwal',
    'Spicy Soyabean Parwal Gravy',
    'Parwal ki Bharwa',
    'Gravy Alu Parwal',
  ],
  "Pea(Matar)" : [
    'Matar Paneer',
    'Aloo Matar Paneer',
    'Methi Matar Malai',
    'Aloo Matar',
    'Matar Kachori',
    'Hara Bhara Kabab',
    'Green Peas Masala',
    'Matar Mushroom',
    'Aloo Gobi Matar',
    'South Indian Mushroom Peas Curry',
    'Khoya Matar Makhana',
    'One Pot Mushroom Matar Makhani',
    'Patta Gobhi Matar',
    'Peas Paratha',
    'Potato Peas Kurma',
    'Aloo Gajar Matar',
    'Gobi Matar',
    'Anjeeri Matar',
    'Gajar Matar',
    'Paneer Peas Bhurji',
    'Chura Matar',
    'Dry Green Peas',
  ],
  "Pumpkin" : [
    'Kaddu ki sabzi',
    'Pumpkin bread',
    'Pumpkin soup',
    'Poosanikai sambar',
    'Lobia pumpkin sambar',
    'Pumpkin erissery',
    'Kaddu ka halwa',
    'Khatta meetha kaddu',
    'Pumpkin kheer',
    'Kaddu ka paratha',
    'Pumpkin bhaji',
    'Eggless pumpkin muffins',
    'Kaddu pakora',
  ],
  "Cauliflower" : [
    'Gobi Masala',
    'Gobi Manchurian',
    'Aloo Gobi',
    'Punjabi Aloo Gobi Sabzi',
    'Dhaba Style Instant Pot Aloo Gobi Gravy',
    'Sindhi Aloo Gobi Methi Tuk',
    'Aloo Gobi Matar',
    'Gobi Paratha',
    'Aloo Gobi Paratha',
    'Fried Cauliflower',
    'Gobi Gajar Shalgam Achar',
    'Tandoori Gobi | Gobi Tikka',
    'Gobi Pakora',
    'Gobi Matar',
    'Gobi Ke Danthal Ki Sabzi',
    'Baked Cauliflower',
    'Cauliflower Kurma',
    'Flower Batata Rassa',
  ],
  "Broccoli" : [
    'Broccoli Baked',
    'Broccoli Salad with French Dressing',
    'Chatpatti Broccoli',
    'Broccoli and Cheddar Crepes',
    'Cream of Broccoli Soup',
    'Broccoli Pasta',
    'Roasted Bell Pepper with Broccoli Salad',
    'Broccoli Soup with Wasabi',
    'Broccoli, Babycorn and Colourful Pasta Salad',
  ],
  "Brinjal" : [
    'Baingan Bharta',
    'Bharli Vangi',
    'Aloo Baingan',
    'Baingan Bhaja',
    'Dum Ke Baingan',
    'Bagara Baingan',
    'Brinjal Sambar',
    'Bharwa Baingan',
    'Baingan Masala',
    'Baingan Ka Chokha',
    'Vangyachi Bhaji',
    'Brinjal Chutney',
    'Baingan Pakoda',
    'Brinjal Fry',
    'Brinjal Kulambu',
  ],
  "Rajma" : [
    'Rajma Curry',
    'Kashmiri Rajma',
    'Refried Beans',
    'Rajma Pakodas',
    'Rajma Kebab',
    'Rajma Aur Kele Ke Kebab',
    'Makhmali Rajma Kebab',
    'Rajma Galouti Kebab',
    'Rajma Aloo Cutlet',
    'Oats and Rajma Cutlet',
    'Chatpata Rajma Wrap',
    'Grilled Rajma Masala Sandwich',
  ],
  "Potato" : [
    'Aloo Paratha',
    'Aloo Chat',
    'Aloo Masala Chat',
    'Dum Aloo',
    'Aloo Paneer Chat',
    'Aloo Tikki',
    'Bengali Aloo Posto',
    'Potatoes in Green Masala',
    'Stuffed Aloo Tamatar in Coconut based paste',
    'Potatoes in Goanese Gravy',
    'Stuffed Potatoes with Paneer',
    'Aloo & Kand Rasawala Shaak',
    'Aloo Puri',
    'Aloo Khaas',
    'Rajasthani Dahi Aloo Sabzi',
    ''
  ],
  "Sweet Potato" : [
    'Candied Sweet Potatoes with Black Sesame',
    'Sweet Potato Medallions',
    'Shakarkandi ki Chaat',
    'Sweet Potato Fries with Amla Aioli',
    'Root Vegetable Tikkis',
    'Sweet Potato Puffs',
    'Sweet Potato and Quinoa Bowl',
    'Sweet Potato Cold Soup',
    'Hassel Back Sweet Potatoes',
  ],
  "Beetroot" : [
    'Beetroot halwa',
    'Beetroot paratha',
    'Beetroot poori',
    'Beetroot bhaji',
    'Veg chops',
    'Beetroot chutney',
    'Beetroot poriyal',
    'Beetroot thoran',
    'Beetroot tikki',
    'Beetroot carrot poriyal',
    'Beetroot carrot raita',
    'Carrot kanji',
    'Beetroot rasam',
  ],

  /* Fruits */

  "Mango" : [
    'Mango Kulfi',
    'Mango Kesari',
    'Amras Recipe',
    'Mango Icecream',
    'Mango Shrikhand',
    'Mango Chutney',
    'Mango Modak',
    'Mango Halwa',
    'Mango cake',
    'Mango Falooda',
  ],
  "Banana" : [
    'Banana Cake',
    'Banana Fritters',
    'Banana Chips',
    'Banana Kebab',
    'Banana and coconut kachouri',
    'Banana Pancakes',
    'Banana Florets',
    'Baked Banana Samosa',
    'Banana and chia tea cakes',
  ],
  "Strawberry" : [
    'Strawberry Cupcake',
    'Strawberry Cheesecake',
    'Strawberry ShortCake',
    'Strawberry Guava Smoothie',
    'Strawberry Souffle',
    'Strawberry Jam',
    'Strawberry Parfait',
    'Strawberry Prumble',
  ],
  "Papaya" : [
    'Papaya Salad',
    'Papaya Cubes',
    'Papaya Kebabs',
    'Santhula',
    'Papaya Halwa',
    'Dalma',
    'Papaya Badam Barfi',
  ],
  "Tomato" : [
    'Tomato Salad',
    'Tomato Curry',
    'Tomato Soup',
    'Tomato Relish',
    'Tomato kadhi',
    'Stuffed Tomato',
    'Chilled Tomato',
  ],
  "Carrot" : [
    'Gajar Ka Halwa',
    'Carrot Paratha',
    'Carrot Rice',
    'Carrot Ginger Soup',
    'Carrot Barfi',
    'Carrot ginger soup',
  ],
  "Gooseberry" : [
    'Gooseberry Pickle',
    'Gooseberry Murabba',
    'Gooseberry Rice',
    'Gooseberry Chutney',
    'Gooseberry Ginger juice',
    'Gooseberry Sabji',
  ],
  "Pomegranate" : [
    'Pomegranate-Braised Short Ribs',
    'Homemade Pomegranate',
    'Herbed Rice with Dates and Pomegranate',
    'Fall Sangria',
    'Raw Kale Salad with Pomegranate',
    'Pomegranate Bulgur Salad',
  ],
  "Lime" : [
    'Sweet Lime Juice , with apple and pomegranate',
    'Soda Lime Juice',
    'Mara mari juice',
    'Red apple sunset',
  ],
  "Guava" : [
    'Guava Cheese',
    'Guava Thandai',
    'Guava Smoothie',
    'Guava Chutney',
    'Amrood ki sabji',
  ],
  "Grape" : [
    'Grape Margarita',
    'Grape lassi',
    'Grape shake',
    'Carrot and black grape juice',
    'Angoor ka raita',
    'Grape Granita',
  ],
  "Custard Apple" : [
    'Custard Apple ice cream',
    'Sitafal Phirni',
    'Sitafal milkshake',
    'Custard Apple smoothie',
    'Apple and custard apple smoothie',
    'Sharife ki rabdi',
  ],
  "Orange" : [
    'Orange Spritz Cookies',
    'Cranberry Orange Walnut Bread',
    'Orange Ricotta Pancakes',
    'Orange-Glazed Pork Loin',
    'Pineapple Orange Cake',
    'Orange-Glazed Pork with Sweet Potatoes',
    'Creamy Orange Caramels',
    'Tilapia with Citrus Sauce',
    'Florida Citrus Meringue Pie',
  ],
  "Watermelon" : [
    'Margarita Watermelon',
    'Watermelon Ice Cream',
    'Watermelon Caprese',
    'Boozy Melon Bites',
    'Skinny Mini Watermelon Cakes',
    'Watermelon Sangria',
    'Mojito Watermelon',
    'Shrimp Skewers with Watermelon and Feta Salad',
  ],
  "Pineapple" : [
    'Grilled Pineapple Sundaes',
    'Pineapple Upside-Down Cake',
    'Skinny Pineapple Cheesecake Bars',
    'Fireball Pineapple',
    'Copycat Dole Pineapple Whip',
    'Creamy Pineapple Sorbet',
    'Coconut Pineapple Yogurt Pops',
  ],
  "Apple" : [
    'Classic Apple Pie',
    'Caramel Apples',
    'Crock-Pot Apple Butter',
    'Apple Pie Bars',
    'Best Apple Crisp',
    'Homemade Apple Cider',
    'Apple Dump Cake',
    'German Apple Cake',
    'Apple Spiced Pancakes',
  ],
  "Mushroom" : [
    'Kombu Barthad (Mushroom Chilly Fry)',
    'Shahi Mushroom',
    'Kalan Milagu',
    'Mushroom Chettinad',
    'Mushroom Kofta in Tomato Gravy',
    'Potato and Mushroom Kebabs',
    'Stuffed Dhaniya & Pepper Mushrooms',
    'Mushroom Utthapam',
    'Matar Mushroom Sukhe',
    'Mushroom Xacuti',
    'Mushroom Palak Kofta',
    'Matar Mushroom',
    'South Indian Mushroom Peas Curry',
    'One Pot Mushroom Matar Makhani',
  ],

  /* Mix-Item */

  "Paneer" : [
    'Shahi Paneer',
    'Palak Paneer',
    'Panner Butter Masala',
    'Matar Paneer',
    'Aloo Matar Paneer',
    'Paneer Tikka',
    'Paneer Tikka Masala',
    'Paneer Tikka Pizza',
    'Paneer Malai Tikka'
    'Tawa Paneer Masala',
    'Kadhai Paneer',
    'Achari Paneer',
    'Achari Paneer Tikka',
    'Hariyali Paneer Tikka',
    'Paneer Pasanda',
    'Paneer Makhani',
    'Aloo Paneer',
    'Aloo Paneer Tikki',
    'Methi Paneer',
    'Methi Malai Paneer',
    'Methi Palak Saag Paneer',
    'Chilli Paneer',
    'Paneer Bhurji',
    'Paneer Palak Bhurji',
    'Paneer Peas Bhurji',
    'Paneer Paratha',
    'Malai Paneer',
    'Paneer Korma',
    'Paneer Manchurian',
    'Paneer Koliwada',
    'Paneer Barfi',
    'Chhola Paneer',
    'Paneer Khurchan',
    'Paneer Amritsari',
    'Paneer Kolhapuri',
    'Paneer Fry',
    'Paneer Pakoda',
    'Mushroom Paneer',
    'Paneer Jalfrezi',
    'Paneer Schezwan',
    'Paneer Kali Mirch',
    'Paneer Cheese Toast',
    'Paneer Sandwich',
    'Paneer Bhurji Sandwich',
    'Paneer Matar Toast Sandwic',
    'Paneer Bread Roll (Baked)',
    'Paneer Pav Bhaji',
    'Paneer Popcorn',
    'Paneer Cutlet With Mix Vegetables',
    'Paneer Pizza',
    'Paneer Biryani',
    'Paneer Pulao',
  ],

  "Chhole" : ['Chhola', 'Chhola Paneer'],
  "Salad" : ['fruit salad', 'papad'],

  /* Non-veg */

  "Egg" : [
    'Egg Curry',
    'Egg Masala',
    'Anda Bhurji',
    'South Indian Egg Curry',
    'Egg Butter Masala',
    'Egg Toast',
    'Spinach Omelette',
    'Egg Paratha',
    'Egg Bonda',
    'Bread Omelette Sandwich',
    'Egg Bhurji Sandwich',
    'Egg Mayo Sandwich',
    'Aloo Egg Curry',
    'Chettinad Egg Curry',
    'Oats Omelette',
    'Kadai Egg Masala',
    'Egg Dosa',
    'Egg Keema',
    'Egg Kurma',
    'Oats Egg Porridge',
    'Egg Pulusu',
    'Egg Roast',
    'Egg Vindaloo',
    'Mushroom Omelette',
    'Paneer Egg Gravy',
    'Tomato Egg Curry',
    'Oats Scambled Eggs(Oats Bhurji)',
  ],
  "Chicken" : [
    'Amritsari chicken masala',
    'Teekha murg',
    'Murg malaiwala',
    'Chicken chettinad',
    'Kerala chicken roast',
    'Kadhai chicken',
    'Chicken chilli',
    'Chicken lollipop',
    'Butter chicken',
    'Chicken dum biryani',
    'Roasted chicken masala',
    'Dahi chicken',
  ],
  "Fish" : [
    'Masala fried pomfret',
    'Fish curry',
    'Fish curry without oil',
    'Popcorn crusted fish fingers',
    'Fish cutlets',
    'Hariyali machhli with pulao',
    'Thai steamed fish',
    'Chettinad fish fry',
    'Fish duglere',
  ],
  "Meat" : [
    'Laziz lamb handi',
    'Galouti kebab',
    'Khatta meat',
    'Parsi mutton cutlets',
    'Rajsthani laal maas',
    'Bhindiwala meat',
    'Dhabe da keema',
    'Rogan josh',
    'Badami lamb korma',
    'Awadhi mutton biryani',
    'Sali boti',
    'Mutton curry',
    'Kosha mangsho',
  ],
  "Pigeon" : [
    'Roasted wood pigeon',
    'Pigeon pies',
    'Pigeon & hedgerow salad',
    'Pigeon & beetroot salad',
  ],
  "Beef" : [
    'Indian fried beef',
    'Beef curry',
    'Beef dry roast',
    'South indian beef curry',
    'Indian spiced Beef stew',
    'Indian spiced Beef Kababs',
  ],
  "Crab" : [
    'classic crab boil',
    'avocado crab boats',
    'hot crab pinwheels',
    'sweet potato and crab',
    'spicy crab salad',
    'crabmeat boats',
    'baked crab rangoons',
    'crab cake',
    'crab crescents',
    'curried crab spread',
  ],
  "Rabbit" : [
    'Stuffed Rabbit Recipes',
    'Rabbit in Mustard Sauce',
    'Braised Rabbit Pie',
    'Kentucky Fried Rabbit',
    'Rabbit Sausage',
    'Slow Roasted Rabbit',
  ],
  "Pork" : [
    'roast pork belly',
    'thai pork salad',
    'pork curry',
    'pork vindaloo',
    'jamaican pork chops',
    'lemon pork',
    'pork sorpotel',
    'banh cuon',
    'pork chops recipe',
  ],
};